---

- name: install dependency packages
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: latest
    dpkg_options: 'force-confnew,force-confdef'
    autoclean: yes
    autoremove: yes
    update_cache: yes
    cache_valid_time: 3600
  vars:
    packages:
    - nginx
    - gzip

- name: add mailpit proxy config
  ansible.builtin.template:
    src: mailpit.conf.j2
    dest: /etc/nginx/sites-available/mailpit.conf
    owner: root
    group: root
    mode: 0644

- name: create a symbolic link for mailpit.conf
  ansible.builtin.file:
    src: /etc/nginx/sites-available/mailpit.conf
    dest: /etc/nginx/sites-enabled/mailpit.conf
    owner: root
    group: root
    state: link


- name: add pgadmin proxy config
  ansible.builtin.template:
    src: pgadmin.conf.j2
    dest: /etc/nginx/sites-available/pgadmin.conf
    owner: root
    group: root
    mode: 0644

- name: create a symbolic link for adminer.conf
  ansible.builtin.file:
    src: /etc/nginx/sites-available/pgadmin.conf
    dest: /etc/nginx/sites-enabled/pgadmin.conf
    owner: root
    group: root
    state: link

- name: add odoo proxy config
  ansible.builtin.template:
    src: odoo.conf.j2
    dest: /etc/nginx/sites-available/odoo.conf
    owner: root
    group: root
    mode: 0644

- name: create a symbolic link for odoo.conf
  ansible.builtin.file:
    src: /etc/nginx/sites-available/odoo.conf
    dest: /etc/nginx/sites-enabled/odoo.conf
    owner: root
    group: root
    state: link

- name: restart nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted

# building a ssl proof proxy setup
# https://www.nginx.com/blog/using-free-ssltls-certificates-from-lets-encrypt-with-nginx/

...
