---
configs:
  memory: "4096"
  cpus: "4"
  ansible_version: "latest"
  ip: "192.168.56.12"
  domain: odoo.lokal
  aliases:
  - www.odoo.lokal
  - shop.odoo.lokal
  - mail.odoo.lokal
  - pgadmin.odoo.lokal
...
